import PageTransition from '@/components/PageTransition'
import Head from 'next/head'
import Link from 'next/link'
type IndexPageProps = {}
type IndexPageRef = React.ForwardedRef<HTMLDivElement>

export default function Home(props: IndexPageProps, ref: IndexPageRef) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageTransition ref={ref}>
          <div id="home" className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            hello
          </div>
        </PageTransition>
      </main>
    </>
  )
}
